services:
  - type: web
    name: pwd-registration-system
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: DB_HOST
        value: your-mysql-host
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: your-database-name
      - key: DB_USERNAME
        value: your-username
      - key: DB_PASSWORD
        value: your-password
